import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import NavSection from "@/components/navsection";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "GizeBook",
  description: "Generated by Kidus",
  icons:"/images/logopro.svg"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const SERVICES_SECTION_ID = "services-list";
  return (
    <html lang="en">
       <link rel="icon" href="/images/logopro.svg" />
     <NavSection servicesSectionId={SERVICES_SECTION_ID}/>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        {children}
      
      </body>
    </html>
  );
}
